"""add_personalized_intro_to_prospects

Revision ID: 4284f4b07285
Revises: e4b9c2d71f3a
Create Date: 2026-04-11 22:35:14.639386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4284f4b07285'
down_revision: Union[str, None] = 'e4b9c2d71f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('personalized_intro', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'personalized_intro')
    # ### end Alembic commands ###
