"""add_email_events

Revision ID: 5e5e6861036a
Revises: b32fcba22143
Create Date: 2026-04-07 21:50:32.049317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5e6861036a'
down_revision: Union[str, None] = 'b32fcba22143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prospect_id', sa.UUID(), nullable=True),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('email_subject', sa.Text(), nullable=True),
    sa.Column('domain_used', sa.String(length=255), nullable=True),
    sa.Column('clicked_url', sa.Text(), nullable=True),
    sa.Column('smartlead_message_id', sa.String(length=255), nullable=True),
    sa.Column('hubspot_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('smartlead_message_id')
    )
    op.create_index('idx_email_events_enrollment', 'email_events', ['enrollment_id'], unique=False)
    op.create_index('idx_email_events_hubspot_sync', 'email_events', ['occurred_at'], unique=False, postgresql_where=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_email_events_hubspot_sync', table_name='email_events', postgresql_where=False)
    op.drop_index('idx_email_events_enrollment', table_name='email_events')
    op.drop_table('email_events')
    # ### end Alembic commands ###
