"""add_sequence_enrollments

Revision ID: 6255ecdd9a8c
Revises: 5e5e6861036a
Create Date: 2026-04-08 10:28:41.181017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6255ecdd9a8c'
down_revision: Union[str, None] = '5e5e6861036a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prospect_id', sa.UUID(), nullable=False),
    sa.Column('smartlead_campaign_id', sa.String(length=50), nullable=False),
    sa.Column('high_intent_campaign_id', sa.String(length=50), nullable=True),
    sa.Column('sequence_type', sa.String(length=20), nullable=False),
    sa.Column('track', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('high_intent_switched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enrollments_active_standard', 'sequence_enrollments', ['status', 'track'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_enrollments_prospect', 'sequence_enrollments', ['prospect_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_enrollments_prospect', table_name='sequence_enrollments')
    op.drop_index('idx_enrollments_active_standard', table_name='sequence_enrollments', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('sequence_enrollments')
    # ### end Alembic commands ###
