"""add wealth_tier and investor_type to prospects

Revision ID: d3811ea7b37c
Revises: 6255ecdd9a8c
Create Date: 2026-04-08 17:23:52.864581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3811ea7b37c'
down_revision: Union[str, None] = '6255ecdd9a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('wealth_tier', sa.String(length=20), nullable=True))
    op.add_column('prospects', sa.Column('investor_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'investor_type')
    op.drop_column('prospects', 'wealth_tier')
    # ### end Alembic commands ###
